// The single source of truth for the 50-state POA strategy (docs/ARCHITECTURE.md §4).
// One universal UPOAA-based body + a per-state variation layer — never 51 forms. Changing how
// a state behaves is a DATA EDIT here, never a new code branch; the engine stays state-agnostic.
//
// Classification confirmed with Taylor 2026-06-17 from docs/research/poa-portability-matrix-50-state.xlsx:
//   - documentPath routes on the FINANCIAL POA framework (UPOAA column). The matrix's medical
//     (UHCDA) data is carried for future use but does NOT drive v1 routing (no medical directive in v1).
//   - Split: 28 UNIVERSAL (UPOAA "Adopted") / 21 UNIVERSAL_PLUS_ADDENDUM ("own statute") / 2 STATE_FORM (MS, TN).
//   - PA, IN, MS confirmed NOT full UPOAA. MS/TN follow the older UDPAA and ship as STATE_FORM.
//
// DATA-CONFIDENCE CAVEAT (per the matrix "Read me" sheet): all rows are build/QA grade. Confirm
// against PRIMARY sources before the tile map makes a public claim. Rows with a known, specific
// open conflict carry `verify: true`:
//   - IN: UPOAA membership was contested across aggregators (resolved: not adopted, IC 30-5); AND its
//         financial execution minimum is contested (matrix "2 witnesses OR notary" vs IC 30-5 "notary
//         AND one witness"). Keep flagged until the ULC enactment page + statute are eyeballed directly.
//   - PA: not UPOAA confirmed (Act 95, 20 Pa.C.S. Ch. 56); its two-witness rule is conditional on
//         signing by mark — verify the execution-minimum string against statute before public display.

export type DocumentPath = 'UNIVERSAL' | 'UNIVERSAL_PLUS_ADDENDUM' | 'STATE_FORM';

/** Financial-POA framework: true = UPOAA adopted; false = own statute / older UDPAA. */
export type UpoaaStatus = boolean | 'unconfirmed';

/** Notary-acknowledgment archetype id (a small set, not 51). Text lives in the templates. */
export type NotaryAck = 'standard' | 'ms' | 'tn';

export interface TilePos {
  row: number;
  col: number;
}

export interface Jurisdiction {
  code: string;
  name: string;
  /** Position in the tile-grid cartogram (approximate, adjustable — it is data). */
  tile: TilePos;
  documentPath: DocumentPath;
  upoaa: UpoaaStatus;
  /** Adopted the Uniform Health-Care Decisions Act (medical). Data only in v1. */
  uhcda: boolean;
  /** Minimum execution for a financial POA (witnesses / notary). */
  financialExecution: string;
  /** Minimum execution for a medical directive. Data only in v1. */
  medicalExecution: string;
  /** Financial-POA governing statute. Verified for MS/TN/PA/IN; generic descriptor elsewhere. */
  statutoryCite: string;
  notaryAck: NotaryAck;
  /** Quirks that change formalities (e.g. burial/cremation extra formalities). */
  specialTriggers: string[];
  /** A specific claim on this row still needs primary-source confirmation before public display. */
  verify: boolean;
  notes: string;
}

const UNIVERSAL_CITE = 'Uniform Power of Attorney Act (state codification)';
const OWN_STATUTE_CITE = 'State power-of-attorney statute';

// Alphabetical by name (matches the source matrix) for easy review.
export const JURISDICTIONS: Jurisdiction[] = [
  {
    code: 'AL',
    name: 'Alabama',
    tile: { row: 6, col: 6 },
    documentPath: 'UNIVERSAL',
    upoaa: true,
    uhcda: true,
    financialExecution: 'Notary; witnesses not required (2 recommended)',
    medicalExecution: '2 witnesses OR notary',
    statutoryCite: UNIVERSAL_CITE,
    notaryAck: 'standard',
    specialTriggers: [],
    verify: false,
    notes: '',
  },
  {
    code: 'AK',
    name: 'Alaska',
    tile: { row: 0, col: 0 },
    documentPath: 'UNIVERSAL_PLUS_ADDENDUM',
    upoaa: false,
    uhcda: true,
    financialExecution: '2 witnesses OR notary',
    medicalExecution: '2 witnesses OR notary',
    statutoryCite: OWN_STATUTE_CITE,
    notaryAck: 'standard',
    specialTriggers: [],
    verify: false,
    notes: '',
  },
  {
    code: 'AZ',
    name: 'Arizona',
    tile: { row: 5, col: 1 },
    documentPath: 'UNIVERSAL_PLUS_ADDENDUM',
    upoaa: false,
    uhcda: false,
    financialExecution: '1 witness + notary',
    medicalExecution: '1 witness OR notary',
    statutoryCite: OWN_STATUTE_CITE,
    notaryAck: 'standard',
    specialTriggers: [],
    verify: false,
    notes: 'Financial requires a witness AND notary — unusual.',
  },
  {
    code: 'AR',
    name: 'Arkansas',
    tile: { row: 5, col: 4 },
    documentPath: 'UNIVERSAL',
    upoaa: true,
    uhcda: false,
    financialExecution: 'Notary; no witnesses',
    medicalExecution: '2 witnesses OR notary',
    statutoryCite: UNIVERSAL_CITE,
    notaryAck: 'standard',
    specialTriggers: [],
    verify: false,
    notes: '',
  },
  {
    code: 'CA',
    name: 'California',
    tile: { row: 4, col: 0 },
    documentPath: 'UNIVERSAL_PLUS_ADDENDUM',
    upoaa: false,
    uhcda: true,
    financialExecution: '2 witnesses OR notary',
    medicalExecution: '2 witnesses OR notary',
    statutoryCite: OWN_STATUTE_CITE,
    notaryAck: 'standard',
    specialTriggers: [],
    verify: false,
    notes: 'Medical directive has its own statutory witness form (special witness eligibility).',
  },
  {
    code: 'CO',
    name: 'Colorado',
    tile: { row: 4, col: 2 },
    documentPath: 'UNIVERSAL',
    upoaa: true,
    uhcda: false,
    financialExecution: 'None required',
    medicalExecution: 'None required',
    statutoryCite: UNIVERSAL_CITE,
    notaryAck: 'standard',
    specialTriggers: [],
    verify: false,
    notes: 'No witness/notary required by statute — execute fully anyway.',
  },
  {
    code: 'CT',
    name: 'Connecticut',
    tile: { row: 3, col: 9 },
    documentPath: 'UNIVERSAL',
    upoaa: true,
    uhcda: false,
    financialExecution: '2 witnesses + notary',
    medicalExecution: '2 witnesses',
    statutoryCite: UNIVERSAL_CITE,
    notaryAck: 'standard',
    specialTriggers: [],
    verify: false,
    notes: '',
  },
  {
    code: 'DE',
    name: 'Delaware',
    tile: { row: 4, col: 9 },
    documentPath: 'UNIVERSAL_PLUS_ADDENDUM',
    upoaa: false,
    uhcda: true,
    financialExecution: '1 witness + notary',
    medicalExecution: '2 witnesses',
    statutoryCite: OWN_STATUTE_CITE,
    notaryAck: 'standard',
    specialTriggers: [],
    verify: false,
    notes: 'First state to adopt the 2023 UHCDA.',
  },
  {
    code: 'DC',
    name: 'District of Columbia',
    tile: { row: 5, col: 8 },
    documentPath: 'UNIVERSAL_PLUS_ADDENDUM',
    upoaa: false,
    uhcda: false,
    financialExecution: 'Notary; no witnesses',
    medicalExecution: '2 witnesses (notary optional)',
    statutoryCite: OWN_STATUTE_CITE,
    notaryAck: 'standard',
    specialTriggers: [],
    verify: false,
    notes: 'Medical witnesses: one must be unrelated and not an heir.',
  },
  {
    code: 'FL',
    name: 'Florida',
    tile: { row: 7, col: 8 },
    documentPath: 'UNIVERSAL_PLUS_ADDENDUM',
    upoaa: false,
    uhcda: false,
    financialExecution: '2 witnesses + notary',
    medicalExecution: '2 witnesses',
    statutoryCite: OWN_STATUTE_CITE,
    notaryAck: 'standard',
    specialTriggers: [],
    verify: false,
    notes:
      'Strict; often rejects out-of-state financial POAs. Strong candidate for bespoke addendum language.',
  },
  {
    code: 'GA',
    name: 'Georgia',
    tile: { row: 6, col: 7 },
    documentPath: 'UNIVERSAL',
    upoaa: true,
    uhcda: false,
    financialExecution: '1 witness + notary',
    medicalExecution: '2 witnesses',
    statutoryCite: UNIVERSAL_CITE,
    notaryAck: 'standard',
    specialTriggers: [],
    verify: false,
    notes: '',
  },
  {
    code: 'HI',
    name: 'Hawaii',
    tile: { row: 7, col: 0 },
    documentPath: 'UNIVERSAL',
    upoaa: true,
    uhcda: true,
    financialExecution: 'Notary; no witnesses',
    medicalExecution: '2 witnesses OR notary',
    statutoryCite: UNIVERSAL_CITE,
    notaryAck: 'standard',
    specialTriggers: [],
    verify: false,
    notes: '',
  },
  {
    code: 'ID',
    name: 'Idaho',
    tile: { row: 2, col: 1 },
    documentPath: 'UNIVERSAL',
    upoaa: true,
    uhcda: false,
    financialExecution: 'Notary; no witnesses',
    medicalExecution: 'None required',
    statutoryCite: UNIVERSAL_CITE,
    notaryAck: 'standard',
    specialTriggers: [],
    verify: false,
    notes: '',
  },
  {
    code: 'IL',
    name: 'Illinois',
    tile: { row: 2, col: 5 },
    documentPath: 'UNIVERSAL_PLUS_ADDENDUM',
    upoaa: false,
    uhcda: false,
    financialExecution: '1 witness + notary',
    medicalExecution: '1 witness',
    statutoryCite: OWN_STATUTE_CITE,
    notaryAck: 'standard',
    specialTriggers: [],
    verify: false,
    notes: 'Permits e-notarized POAs.',
  },
  {
    code: 'IN',
    name: 'Indiana',
    tile: { row: 3, col: 5 },
    documentPath: 'UNIVERSAL_PLUS_ADDENDUM',
    upoaa: false,
    uhcda: false,
    financialExecution: '2 witnesses OR notary',
    medicalExecution: 'Notary',
    statutoryCite: 'Ind. Code 30-5',
    notaryAck: 'standard',
    specialTriggers: [],
    verify: true,
    notes:
      'Not UPOAA (IC 30-5), resolved after aggregators conflicted. Execution minimum also contested: matrix "2 witnesses OR notary" vs IC 30-5 "notary AND one witness" — verify against statute before public display.',
  },
  {
    code: 'IA',
    name: 'Iowa',
    tile: { row: 3, col: 4 },
    documentPath: 'UNIVERSAL',
    upoaa: true,
    uhcda: false,
    financialExecution: '2 witnesses + notary',
    medicalExecution: '2 witnesses + notary',
    statutoryCite: UNIVERSAL_CITE,
    notaryAck: 'standard',
    specialTriggers: [],
    verify: false,
    notes: '',
  },
  {
    code: 'KS',
    name: 'Kansas',
    tile: { row: 5, col: 3 },
    documentPath: 'UNIVERSAL_PLUS_ADDENDUM',
    upoaa: false,
    uhcda: false,
    financialExecution: '2 witnesses OR notary (notary recommended)',
    medicalExecution: '2 witnesses OR notary',
    statutoryCite: OWN_STATUTE_CITE,
    notaryAck: 'standard',
    specialTriggers: [],
    verify: false,
    notes: '',
  },
  {
    code: 'KY',
    name: 'Kentucky',
    tile: { row: 4, col: 5 },
    documentPath: 'UNIVERSAL',
    upoaa: true,
    uhcda: false,
    financialExecution: 'Notary; no witnesses (since 2018)',
    medicalExecution: '2 witnesses OR notary',
    statutoryCite: UNIVERSAL_CITE,
    notaryAck: 'standard',
    specialTriggers: [],
    verify: false,
    notes: '',
  },
  {
    code: 'LA',
    name: 'Louisiana',
    tile: { row: 6, col: 4 },
    documentPath: 'UNIVERSAL_PLUS_ADDENDUM',
    upoaa: false,
    uhcda: false,
    financialExecution: '2 witnesses + notary',
    medicalExecution: '2 witnesses',
    statutoryCite: OWN_STATUTE_CITE,
    notaryAck: 'standard',
    specialTriggers: [],
    verify: false,
    notes:
      'Civil-law authentic-act formalities differ from common-law states. Strong candidate for bespoke addendum language.',
  },
  {
    code: 'ME',
    name: 'Maine',
    tile: { row: 0, col: 10 },
    documentPath: 'UNIVERSAL',
    upoaa: true,
    uhcda: true,
    financialExecution: 'Notary; no witnesses',
    medicalExecution: '2 witnesses',
    statutoryCite: UNIVERSAL_CITE,
    notaryAck: 'standard',
    specialTriggers: [],
    verify: false,
    notes: '',
  },
  {
    code: 'MD',
    name: 'Maryland',
    tile: { row: 4, col: 8 },
    documentPath: 'UNIVERSAL',
    upoaa: true,
    uhcda: false,
    financialExecution: '2 witnesses + notary',
    medicalExecution: '2 witnesses',
    statutoryCite: UNIVERSAL_CITE,
    notaryAck: 'standard',
    specialTriggers: [],
    verify: false,
    notes: '',
  },
  {
    code: 'MA',
    name: 'Massachusetts',
    tile: { row: 2, col: 10 },
    documentPath: 'UNIVERSAL_PLUS_ADDENDUM',
    upoaa: false,
    uhcda: false,
    financialExecution: '2 witnesses; notary not required (recommended)',
    medicalExecution: '2 witnesses',
    statutoryCite: OWN_STATUTE_CITE,
    notaryAck: 'standard',
    specialTriggers: [],
    verify: false,
    notes: '',
  },
  {
    code: 'MI',
    name: 'Michigan',
    tile: { row: 2, col: 7 },
    documentPath: 'UNIVERSAL',
    upoaa: true,
    uhcda: false,
    financialExecution: '2 witnesses OR notary',
    medicalExecution: '2 witnesses',
    statutoryCite: UNIVERSAL_CITE,
    notaryAck: 'standard',
    specialTriggers: [],
    verify: false,
    notes: 'Most recent UPOAA adopter (eff. July 1, 2024).',
  },
  {
    code: 'MN',
    name: 'Minnesota',
    tile: { row: 2, col: 4 },
    documentPath: 'UNIVERSAL_PLUS_ADDENDUM',
    upoaa: false,
    uhcda: false,
    financialExecution: 'Notary; no witnesses',
    medicalExecution: '2 witnesses OR notary',
    statutoryCite: OWN_STATUTE_CITE,
    notaryAck: 'standard',
    specialTriggers: [],
    verify: false,
    notes: '',
  },
  {
    code: 'MS',
    name: 'Mississippi',
    tile: { row: 6, col: 5 },
    documentPath: 'STATE_FORM',
    upoaa: false,
    uhcda: true,
    financialExecution: 'Notary; no witnesses',
    medicalExecution: '2 witnesses OR notary',
    statutoryCite: 'Miss. Code Ann. §§ 87-3-101 to 87-3-115 (Uniform Durable POA Act)',
    notaryAck: 'ms',
    specialTriggers: [],
    verify: false,
    notes:
      'Older Uniform Durable POA Act, not full UPOAA. TCB home state. Ships a verified native form.',
  },
  {
    code: 'MO',
    name: 'Missouri',
    tile: { row: 4, col: 4 },
    documentPath: 'UNIVERSAL_PLUS_ADDENDUM',
    upoaa: false,
    uhcda: false,
    financialExecution: 'Notary; no witnesses',
    medicalExecution: 'Notary (2 witnesses if burial/cremation)',
    statutoryCite: OWN_STATUTE_CITE,
    notaryAck: 'standard',
    specialTriggers: ['burial-cremation'],
    verify: false,
    notes: 'Burial/cremation authority triggers extra witnesses.',
  },
  {
    code: 'MT',
    name: 'Montana',
    tile: { row: 2, col: 2 },
    documentPath: 'UNIVERSAL',
    upoaa: true,
    uhcda: false,
    financialExecution: 'Notary; no witnesses',
    medicalExecution: '2 witnesses',
    statutoryCite: UNIVERSAL_CITE,
    notaryAck: 'standard',
    specialTriggers: [],
    verify: false,
    notes: '',
  },
  {
    code: 'NE',
    name: 'Nebraska',
    tile: { row: 4, col: 3 },
    documentPath: 'UNIVERSAL',
    upoaa: true,
    uhcda: false,
    financialExecution: 'Notary; no witnesses',
    medicalExecution: '2 witnesses OR notary',
    statutoryCite: UNIVERSAL_CITE,
    notaryAck: 'standard',
    specialTriggers: [],
    verify: false,
    notes: '',
  },
  {
    code: 'NV',
    name: 'Nevada',
    tile: { row: 3, col: 1 },
    documentPath: 'UNIVERSAL',
    upoaa: true,
    uhcda: false,
    financialExecution: '2 witnesses + notary',
    medicalExecution: '2 witnesses OR notary (notary if burial/cremation)',
    statutoryCite: UNIVERSAL_CITE,
    notaryAck: 'standard',
    specialTriggers: ['burial-cremation'],
    verify: false,
    notes: 'Burial/cremation authority triggers notary.',
  },
  {
    code: 'NH',
    name: 'New Hampshire',
    tile: { row: 1, col: 10 },
    documentPath: 'UNIVERSAL',
    upoaa: true,
    uhcda: false,
    financialExecution: 'Notary; no witnesses',
    medicalExecution: '2 witnesses OR notary',
    statutoryCite: UNIVERSAL_CITE,
    notaryAck: 'standard',
    specialTriggers: [],
    verify: false,
    notes: '',
  },
  {
    code: 'NJ',
    name: 'New Jersey',
    tile: { row: 3, col: 8 },
    documentPath: 'UNIVERSAL_PLUS_ADDENDUM',
    upoaa: false,
    uhcda: false,
    financialExecution: 'Notary; no witnesses',
    medicalExecution: '2 witnesses OR notary',
    statutoryCite: OWN_STATUTE_CITE,
    notaryAck: 'standard',
    specialTriggers: [],
    verify: false,
    notes: '',
  },
  {
    code: 'NM',
    name: 'New Mexico',
    tile: { row: 5, col: 2 },
    documentPath: 'UNIVERSAL',
    upoaa: true,
    uhcda: true,
    financialExecution: 'Notary; no witnesses',
    medicalExecution: 'None required (recommended)',
    statutoryCite: UNIVERSAL_CITE,
    notaryAck: 'standard',
    specialTriggers: [],
    verify: false,
    notes: 'First state to adopt UPOAA (2007).',
  },
  {
    code: 'NY',
    name: 'New York',
    tile: { row: 2, col: 9 },
    documentPath: 'UNIVERSAL_PLUS_ADDENDUM',
    upoaa: false,
    uhcda: false,
    financialExecution: '2 witnesses + notary',
    medicalExecution: '2 witnesses',
    statutoryCite: OWN_STATUTE_CITE,
    notaryAck: 'standard',
    specialTriggers: [],
    verify: false,
    notes:
      'Highly formal; statutory form recommended. Strong candidate for bespoke addendum language.',
  },
  {
    code: 'NC',
    name: 'North Carolina',
    tile: { row: 5, col: 6 },
    documentPath: 'UNIVERSAL',
    upoaa: true,
    uhcda: false,
    financialExecution: 'Notary; no witnesses',
    medicalExecution: '2 witnesses + notary',
    statutoryCite: UNIVERSAL_CITE,
    notaryAck: 'standard',
    specialTriggers: [],
    verify: false,
    notes: '',
  },
  {
    code: 'ND',
    name: 'North Dakota',
    tile: { row: 2, col: 3 },
    documentPath: 'UNIVERSAL_PLUS_ADDENDUM',
    upoaa: false,
    uhcda: false,
    financialExecution: 'Notary; no witnesses',
    medicalExecution: '2 witnesses OR notary',
    statutoryCite: OWN_STATUTE_CITE,
    notaryAck: 'standard',
    specialTriggers: [],
    verify: false,
    notes: '',
  },
  {
    code: 'OH',
    name: 'Ohio',
    tile: { row: 3, col: 6 },
    documentPath: 'UNIVERSAL',
    upoaa: true,
    uhcda: false,
    financialExecution: 'Notary; no witnesses',
    medicalExecution: '2 witnesses OR notary',
    statutoryCite: UNIVERSAL_CITE,
    notaryAck: 'standard',
    specialTriggers: [],
    verify: false,
    notes: '',
  },
  {
    code: 'OK',
    name: 'Oklahoma',
    tile: { row: 6, col: 3 },
    documentPath: 'UNIVERSAL_PLUS_ADDENDUM',
    upoaa: false,
    uhcda: false,
    financialExecution: 'Neither required (notary recommended)',
    medicalExecution: '2 witnesses',
    statutoryCite: OWN_STATUTE_CITE,
    notaryAck: 'standard',
    specialTriggers: [],
    verify: false,
    notes: '',
  },
  {
    code: 'OR',
    name: 'Oregon',
    tile: { row: 3, col: 0 },
    documentPath: 'UNIVERSAL_PLUS_ADDENDUM',
    upoaa: false,
    uhcda: false,
    financialExecution: 'Notary; no witnesses',
    medicalExecution: '2 witnesses OR notary',
    statutoryCite: OWN_STATUTE_CITE,
    notaryAck: 'standard',
    specialTriggers: [],
    verify: false,
    notes: '',
  },
  {
    code: 'PA',
    name: 'Pennsylvania',
    tile: { row: 3, col: 7 },
    documentPath: 'UNIVERSAL_PLUS_ADDENDUM',
    upoaa: false,
    uhcda: false,
    financialExecution: '2 witnesses + notary',
    medicalExecution: '2 witnesses',
    statutoryCite: '20 Pa.C.S. Ch. 56 (§ 5601 et seq.)',
    notaryAck: 'standard',
    specialTriggers: [],
    verify: true,
    notes:
      'Not UPOAA; own statute (Act 95, 20 Pa.C.S. Ch. 56), confirmed. Two-witness rule is conditional on signing by mark — verify execution-minimum string against statute before public display.',
  },
  {
    code: 'RI',
    name: 'Rhode Island',
    tile: { row: 3, col: 10 },
    documentPath: 'UNIVERSAL_PLUS_ADDENDUM',
    upoaa: false,
    uhcda: false,
    financialExecution: 'Notary; no witnesses',
    medicalExecution: '2 witnesses OR notary (notary if burial/cremation)',
    statutoryCite: OWN_STATUTE_CITE,
    notaryAck: 'standard',
    specialTriggers: ['burial-cremation'],
    verify: false,
    notes: '',
  },
  {
    code: 'SC',
    name: 'South Carolina',
    tile: { row: 5, col: 7 },
    documentPath: 'UNIVERSAL',
    upoaa: true,
    uhcda: false,
    financialExecution: '2 witnesses + notary',
    medicalExecution: '2 witnesses + notary',
    statutoryCite: UNIVERSAL_CITE,
    notaryAck: 'standard',
    specialTriggers: [],
    verify: false,
    notes: '',
  },
  {
    code: 'SD',
    name: 'South Dakota',
    tile: { row: 3, col: 3 },
    documentPath: 'UNIVERSAL_PLUS_ADDENDUM',
    upoaa: false,
    uhcda: false,
    financialExecution: 'Notary; no witnesses',
    medicalExecution: '2 witnesses OR notary',
    statutoryCite: OWN_STATUTE_CITE,
    notaryAck: 'standard',
    specialTriggers: [],
    verify: false,
    notes: '',
  },
  {
    code: 'TN',
    name: 'Tennessee',
    tile: { row: 5, col: 5 },
    documentPath: 'STATE_FORM',
    upoaa: false,
    uhcda: true,
    financialExecution: '2 witnesses OR notary',
    medicalExecution: '2 witnesses OR notary',
    statutoryCite: 'Tenn. Code Ann. §§ 34-6-101 to 34-6-112 (Uniform Durable POA Act)',
    notaryAck: 'tn',
    specialTriggers: [],
    verify: false,
    notes:
      'Own statute (UDPAA, not UPOAA). Bundled in the state-form path alongside MS. Ships a verified native form.',
  },
  {
    code: 'TX',
    name: 'Texas',
    tile: { row: 7, col: 3 },
    documentPath: 'UNIVERSAL',
    upoaa: true,
    uhcda: false,
    financialExecution: 'Notary; no witnesses',
    medicalExecution: '2 witnesses OR notary (both if burial/cremation)',
    statutoryCite: UNIVERSAL_CITE,
    notaryAck: 'standard',
    specialTriggers: ['burial-cremation'],
    verify: false,
    notes: 'Burial/cremation authority triggers witnesses + notary.',
  },
  {
    code: 'UT',
    name: 'Utah',
    tile: { row: 4, col: 1 },
    documentPath: 'UNIVERSAL',
    upoaa: true,
    uhcda: false,
    financialExecution: 'Notary; no witnesses',
    medicalExecution: '1 witness (2 if burial/cremation)',
    statutoryCite: UNIVERSAL_CITE,
    notaryAck: 'standard',
    specialTriggers: ['burial-cremation'],
    verify: false,
    notes: '',
  },
  {
    code: 'VT',
    name: 'Vermont',
    tile: { row: 1, col: 9 },
    documentPath: 'UNIVERSAL',
    upoaa: true,
    uhcda: false,
    financialExecution: '1 witness + notary',
    medicalExecution: '2 witnesses',
    statutoryCite: UNIVERSAL_CITE,
    notaryAck: 'standard',
    specialTriggers: [],
    verify: false,
    notes: 'Adopted UPOAA in 2023.',
  },
  {
    code: 'VA',
    name: 'Virginia',
    tile: { row: 4, col: 7 },
    documentPath: 'UNIVERSAL',
    upoaa: true,
    uhcda: false,
    financialExecution: 'Notary; no witnesses',
    medicalExecution: '2 witnesses (notary if burial/cremation)',
    statutoryCite: UNIVERSAL_CITE,
    notaryAck: 'standard',
    specialTriggers: ['burial-cremation'],
    verify: false,
    notes: '',
  },
  {
    code: 'WA',
    name: 'Washington',
    tile: { row: 2, col: 0 },
    documentPath: 'UNIVERSAL',
    upoaa: true,
    uhcda: false,
    financialExecution: '2 witnesses OR notary',
    medicalExecution: '2 witnesses OR notary',
    statutoryCite: UNIVERSAL_CITE,
    notaryAck: 'standard',
    specialTriggers: [],
    verify: false,
    notes: '',
  },
  {
    code: 'WV',
    name: 'West Virginia',
    tile: { row: 4, col: 6 },
    documentPath: 'UNIVERSAL',
    upoaa: true,
    uhcda: false,
    financialExecution: '2 witnesses + notary',
    medicalExecution: '2 witnesses + notary',
    statutoryCite: UNIVERSAL_CITE,
    notaryAck: 'standard',
    specialTriggers: [],
    verify: false,
    notes: '',
  },
  {
    code: 'WI',
    name: 'Wisconsin',
    tile: { row: 2, col: 6 },
    documentPath: 'UNIVERSAL',
    upoaa: true,
    uhcda: false,
    financialExecution: 'Notary; no witnesses',
    medicalExecution: '2 witnesses',
    statutoryCite: UNIVERSAL_CITE,
    notaryAck: 'standard',
    specialTriggers: [],
    verify: false,
    notes: '',
  },
  {
    code: 'WY',
    name: 'Wyoming',
    tile: { row: 3, col: 2 },
    documentPath: 'UNIVERSAL',
    upoaa: true,
    uhcda: true,
    financialExecution: 'Notary; no witnesses',
    medicalExecution: '2 witnesses OR notary',
    statutoryCite: UNIVERSAL_CITE,
    notaryAck: 'standard',
    specialTriggers: [],
    verify: false,
    notes: '',
  },
];

const CODES = new Set(JURISDICTIONS.map((j) => j.code));

export function isJurisdictionCode(code: string): boolean {
  return CODES.has(code);
}

export function getJurisdiction(code: string): Jurisdiction | undefined {
  return JURISDICTIONS.find((j) => j.code === code);
}

// ---- documentPath legend (the tile-map key). Colors mirror the brand `path.*` tokens.
//      ES strings are DRAFT, pending the phase-8 native review. ----

export interface PathLegendEntry {
  path: DocumentPath;
  color: string;
  bg: string;
  labelEn: string;
  labelEs: string;
  descriptionEn: string;
  descriptionEs: string;
}

export const DOCUMENT_PATH_LEGEND: PathLegendEntry[] = [
  {
    path: 'UNIVERSAL',
    color: '#3F6B53',
    bg: '#E6EFE9',
    labelEn: 'Ready to use',
    labelEs: 'Listo para usar',
    descriptionEn: 'Your state works with our standard form.',
    descriptionEs: 'Tu estado funciona con nuestro formulario estándar.',
  },
  {
    path: 'UNIVERSAL_PLUS_ADDENDUM',
    color: '#BE8A3E',
    bg: '#F5ECDB',
    labelEn: 'One extra page',
    labelEs: 'Una página extra',
    descriptionEn: 'Your state needs a short add-on page we include.',
    descriptionEs: 'Tu estado necesita una página adicional que incluimos.',
  },
  {
    path: 'STATE_FORM',
    color: '#4A5A6B',
    bg: '#E7ECF1',
    labelEn: "Your state's own form",
    labelEs: 'Formulario propio de tu estado',
    descriptionEn: 'Your state requires its own official form.',
    descriptionEs: 'Tu estado requiere su propio formulario oficial.',
  },
];
